### ISSUE TITLE
Push rootlets segmentations

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model-spinal-rootlets#33]
Currently, the manual rootlets GT segmentations (n=36; see [D5.tsv](https://github.com/ivadomed/model-spinal-rootlets/blob/main/training/dataset_creation/D5.tsv)) used to train the latest model M5 are stored locally on duke (`~/duke/projects/ml_spinal_rootlets/datasets/Dataset012_M5`) organized according to the nnUNet format:

```console
├── imagesTr
│   ├── sub-002_ses-headNormal_000_0000.nii.gz
│   ├── sub-003_ses-headNormal_002_0000.nii.gz
...
├── imagesTs
│   ├── sub-007_ses-headNormal_009_0000.nii.gz
│   ├── sub-010_ses-headUp_015_0000.nii.gz
│   ├── sub-amu02_215_0000.nii.gz
│   ├── sub-barcelona01_212_0000.nii.gz
│   └── sub-brnoUhb03_209_0000.nii.gz
├── labelsTr
│   ├── sub-002_ses-headNormal_000.nii.gz
│   ├── sub-003_ses-headNormal_002.nii.gz
...
└── labelsTs
    ├── sub-007_ses-headNormal_009.nii.gz
    ├── sub-010_ses-headUp_015.nii.gz
    ├── sub-amu02_215.nii.gz
    ├── sub-barcelona01_212.nii.gz
    └── sub-brnoUhb03_209.nii.gz
```

## TODO

- [x] convert the GT used for training (`labelsTr`) from nnUNet format to BIDS using [convert_nnUNetV2_to_bids.py](https://github.com/ivadomed/utilities/blob/main/dataset_conversion/convert_nnUNetV2_to_bids.py)
- [x] choose the proper suffix -- according to [our intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#examples-and-use-cases), it should be `sub-001_acq-sag_T2w_label-rootlets_dseg.nii.gz`
- [x] push the GT to [spine-generic multi-subject](https://github.com/spine-generic/data-multi-subject) - done in https://github.com/spine-generic/data-multi-subject/pull/158
- [x] push the GT to [openneuro/ds004507](https://openneuro.org/datasets/ds004507/versions/1.0.1) - done in https://openneuro.org/datasets/ds004507/versions/1.1.0

Note that for five testing images (`imagesTs`) we have available reference STAPLE segmentations (`labelsTs`) and also manual segmentations from 4 raters. These segs are already BIDSified (`/duke/projects/ml_spinal_rootlets/datasets/inter-rater_variability`):

<details><summary>details</summary>

```console
derivatives/labels
├── sub-007
│   └── ses-headNormal
│       └── anat
│           ├── sub-007_ses-headNormal_T2w_label-rootlet_rater1.nii.gz
│           ├── sub-007_ses-headNormal_T2w_label-rootlet_rater2.nii.gz
│           ├── sub-007_ses-headNormal_T2w_label-rootlet_rater3.nii.gz
│           ├── sub-007_ses-headNormal_T2w_label-rootlet_rater4.nii.gz
│           └── sub-007_ses-headNormal_T2w_label-rootlet_staple.nii.gz
├── sub-010
│   └── ses-headUp
│       └── anat
│           ├── sub-010_ses-headUp_T2w_label-rootlet_rater1.nii.gz
│           ├── sub-010_ses-headUp_T2w_label-rootlet_rater2.nii.gz
│           ├── sub-010_ses-headUp_T2w_label-rootlet_rater3.nii.gz
│           ├── sub-010_ses-headUp_T2w_label-rootlet_rater4.nii.gz
│           └── sub-010_ses-headUp_T2w_label-rootlet_staple.nii.gz
├── sub-amu02
│   └── anat
│       ├── sub-amu02_T2w_label-rootlet_rater1.nii.gz
│       ├── sub-amu02_T2w_label-rootlet_rater2.nii.gz
│       ├── sub-amu02_T2w_label-rootlet_rater3.nii.gz
│       ├── sub-amu02_T2w_label-rootlet_rater4.nii.gz
│       └── sub-amu02_T2w_label-rootlet_staple.nii.gz
├── sub-barcelona01
│   └── anat
│       ├── sub-barcelona01_T2w_label-rootlet_rater1.nii.gz
│       ├── sub-barcelona01_T2w_label-rootlet_rater2.nii.gz
│       ├── sub-barcelona01_T2w_label-rootlet_rater3.nii.gz
│       ├── sub-barcelona01_T2w_label-rootlet_rater4.nii.gz
│       └── sub-barcelona01_T2w_label-rootlet_staple.nii.gz
└── sub-brnoUhb03
    └── anat
        ├── sub-brnoUhb03_T2w_label-rootlet_rater1.nii.gz
        ├── sub-brnoUhb03_T2w_label-rootlet_rater2.nii.gz
        ├── sub-brnoUhb03_T2w_label-rootlet_rater3.nii.gz
        ├── sub-brnoUhb03_T2w_label-rootlet_rater4.nii.gz
        └── sub-brnoUhb03_T2w_label-rootlet_staple.nii.gz
```

</details>

**Comment by jcohenadad** [comment]
> choose the proper suffix -- according to [our intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#examples-and-use-cases), it should be sub-001_acq-sag_T2w_label-rootlets_dseg.nii.gz

we also need to find a way to distinguish rater1, rater2, staple, etc. Maybe @NathanMolinier has some ideas

**Comment by NathanMolinier** [comment]
> we also need to find a way to distinguish rater1, rater2, staple, etc. Maybe @NathanMolinier has some ideas

To differentiate between raters and staple, I think that we could use the entity `desc-XXX` (`desc-rater1`, `desc-staple` etc.). See BIDS [specification](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#desc).

Also, if we want to clarify the meaning of these `desc` entities, we could also add a file `descriptions.tsv` at the root of the derivative folder as shown on our intranet [here](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#derivatives-labels-descriptions-tsv).

**Comment by valosekj** [comment]
Completed within:
- https://github.com/spine-generic/data-multi-subject/pull/158
- https://openneuro.org/datasets/ds004507/versions/1.1.0
