### ISSUE TITLE
First results training ivadomed

### ISSUE THREAD

**Issue by tzebre** [ivadomed/model-spinal-rootlets#4]
## 1) Data
Spinal roots are only visible on T2w MRI. 
Original datas are available here :[ds004507/versions/1.0.1]( https://openneuro.org/datasets/ds004507/versions/1.0.1)
Since no dataset with mask on the spinal root is available, a manual labeling has been done for subjects of this dataset (16 MRI, headNormal and headUp).
Data available in duke/temp/theo_root/ds004507 (tag v1.0)

## 2) Methods 
Using ivadomed, a uNET model was trained with [config.json](https://github.com/ivadomed/model-spinal-rootlets/blob/main/config.json)

## 3) Results 
Available in duke/temp/theo_root/seg_human_root_t2w/
After 100 epochs we have bad results. 
[WandB report](https://wandb.ai/teomatieu/seg_human_root_t2w_/reports/V1-root-seg-model---Vmlldzo0NDU5MTQw)
<img width="862" alt="Capture d’écran 2023-05-25 à 11 18 45" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/b672004f-7e1e-4d17-8b54-d3b86cd910e9">
True positive, False positive, False negative (1:red, 2:orange and 3:yellow) results of the model, the manual mask is in blue 

## 4) Discussion 
Possible problems:
### a) True positive that is not coherent with the manual mask
In the pred-TP-FP-FN file, some voxels in red (true positive) are not in the manual mask, so it's False Positive not True Positive  . 
### b) Manual labeling problem, not accurate:
- [Script](https://github.com/ivadomed/model-spinal-rootlets/blob/main/open_mask.sh) made to open and check what has been done.
- Sometimes sky when paying with contrast, its difficult to locate the spinal root (lower cervical and thoracic level).
## TODO
- [ ] Understand TP problem
- [ ] Review all manually labeled data 
- [ ] Try to tune the model better 
- [ ] Label more MRI

**Comment by tzebre** [comment]
This was a 2D model so i'm trying with a 3D model
